name: Build/Deploy App

on:
  push:
    branches: [ deploy-ci ]
  pull_request:
    branches: [ deploy-ci ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.1.1
      with:
        channel: 'dev'
      env:
        KEY_JKS: ${{ secrets.UPLOAD_KEYSTORE }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: echo $UPLOAD_KEYSTORE > android/upload-keystore.jks && flutter build apk --release
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk 