name: Build/Deploy App

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/your_signing_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build prod
        run: ./gradlew app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/


# jobs:
#   Build-Image:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - uses: actions/setup-java@v1
#       with:
#         java-version: '12.x'
#     - uses: subosito/flutter-action@v1
#       with:
#         flutter-version: '2.10.2'
#     # - run: flutter clean
#     - name: Install Dependencies
#       run:  | 
#         echo "${{secrets.UPLOAD_KEYSTORE}}" > upload-keystore.jks
#         mv upload-keystore.jks ./android
#         ls ./android
#     - run: flutter build apk --release
#     - run: flutter build appbundle  
#     - name: Push to Releases
#       uses: ncipollo/release-action@v1
#       with:
#         # artifacts: "build/app/outputs/apk/release/*,build/app/outputs/bundle/release/*"
#         artifacts: "build/app/outputs/bjundle/release/*"
#         tag: v1.0.${{ github.run_number }}
#         token: ${{ secrets.GITHUB_TOKEN }}
      
      

  # Build-Image:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
  #     with:j
  #       php-version: '8.1'
  #   - uses: actions/checkout@v2

  #   - name: Install Dependencies
  #     run: composer install --ignore-platform-reqs