name: Build/Deploy App

on:
  push:
    branches: [ deploy-ci ]
  pull_request:
    branches: [ deploy-ci ]

env:
  KEY_JKS: ${{ secrets.UPLOAD_KEYSTORE }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  ALIAS_PASSWORD: ${{ secrets.STORE_PASSWORD }}

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Define environment variables
      uses: actions/checkout@v1
    - name: Define actions
      uses: actions/checkout@v1
    - name: setup-jav
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # - name: Upload Secrets
    #   uses: subosito/flutter-action@v1.1.1
    #   # run: echo $UPLOAD_KEYSTORE > android/upload-keystore.jks 
    #   run: ls
    - name: Directory Content
      run: ls android/
    - name: Upload Secret Key
      run: echo $UPLOAD_KEYSTORE > android/upload-keystore.jks 
    - name: Directory Content 2
      run: ls android/ 
      
    # - name: Create APK package
      # run: flutter build apk --release
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.2'
        channel: 'stable'
    - run: flutter --version

    - name: Build  APK
      run: flutter build apk

    - name: Save APK File
      uses: actions/upload-artifact@v3
      with:
        name: tactictrade-apk
        path: "build/app/outputs/apk/release/*"

    - name: Build appbundle
      run: flutter build appbundle

    - name: Save Bundle File
      uses: actions/upload-artifact@v3      
      with:
        name: tactictrade-appbundle
        path: "build/app/outputs/bundle/release/*"



#       - name: Install Dependencies
#         run:  | 
#           echo "${{secrets.UPLOAD_KEYSTORE}}" > upload-keystore.jks
    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: release-apk
    #     path: build/app/outputs/apk/release/app-release.apk 


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Decode Keystore
#         id: decode_keystore
#         uses: timheuer/base64-to-file@v1
#         with:
#           fileName: 'android/upload-keystore.jks'
#           encodedString: ${{ secrets.KEYSTORE }}
#       - uses: actions/checkout@v1
#       - uses: actions/setup-java@v1
#         with:
#           java-version: '12.x'
#       - uses: subosito/flutter-action@v1
#         with:
#           flutter-version: '2.10.2'
#       # - run: flutter clean
#       - name: Install Dependencies
#         run:  | 
#           echo "${{secrets.UPLOAD_KEYSTORE}}" > upload-keystore.jks
#           mv upload-keystore.jks ./android
#           ls ./android
#       - run: flutter build apk --release
#       - run: flutter build appbundle  
#       - name: Push to Releases
#         uses: ncipollo/release-action@v1
#         with:
#           # artifacts: "build/app/outputs/apk/release/*,build/app/outputs/bundle/release/*"
#           artifacts: "build/app/outputs/bjundle/release/*"
#           tag: v1.0.${{ github.run_number }}
#           token: ${{ secrets.GITHUB_TOKEN }}
      
      

#   # Build-Image:
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #   - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
#   #     with:j
#   #       php-version: '8.1'
#   #   - uses: actions/checkout@v2

