name: Build/Deploy App

on:
  push:
    branches: [ deploy-ci ]
  pull_request:
    branches: [ deploy-ci ]

env:
  KEY_JKS: ${{ secrets.UPLOAD_KEYSTORE }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  ALIAS_PASSWORD: ${{ secrets.STORE_PASSWORD }}
  VERSION_NAME: '1.0.$GITHUB_RUN_ID'
  VERSION_CODE: '$GITHUB_RUN_ID'



jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Define environment variables
      uses: actions/checkout@v1
    - name: Define actions
      uses: actions/checkout@v1
    - name: setup-jav
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Create Version Number
      run: echo "VERSION '1.0.$GITHUB_RUN_ID'"

    - name: Directory Content
      run: ls android/
    - name: Upload Secret Key
      run: echo $UPLOAD_KEYSTORE > android/upload-keystore.jks 
    - name: Directory Content 2
      run: ls android/ 
      
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.2'
        channel: 'stable'
    - run: flutter --version

    - name: Build  APK
      run: flutter build apk --build-name='1.0.$GITHUB_RUN_ID' --build-number=$GITHUB_RUN_ID

    - name: Save APK File
      uses: actions/upload-artifact@v3
      with:
        name: tactictrade-apk
        path: "build/app/outputs/apk/release/*"

    - name: Build appbundle
      run: flutter build appbundle --build-name='1.0.$GITHUB_RUN_ID' --build-number=$GITHUB_RUN_ID

    - name: Save Bundle File
      uses: actions/upload-artifact@v3      
      with:
        name: tactictrade-appbundle
        path: "build/app/outputs/bundle/release/*"


  # flutter build appbundle --build-name=1.0.3 --build-number=3

# keytool -list -v \ -alias androiddebugkey -keystore ~/.android/debug.keystore

# $ java -jar pepk.jar --keystore=foo.keystore --alias=foo --output=output.zip --include-cert --encryptionkey=
# docker run --rm -it -v $(pwd):$(pwd) -w $(pwd) yongjhih/pepk --keystore=/Users/ceciliocannavaciuolo/.android/debug.keystore  --alias=foo --output=output.zip --encryptionkey=eb10fe8f7c7c9df715022017b00c6471f8ba8170b13049a11e6c09ffe3056a104a3bbe4ac5a955f4ba4fe93fc8cef27558a3eb9d2a529a2092761fb833b656cd48b9de6a --include-cert


# java -jar pepk.jar --keystore=/Users/ceciliocannavaciuolo/.android/debug.keystore  --alias=androiddebugkey --output=output.zip --include-cert --encryptionkey=eb10fe8f7c7c9df715022017b00c6471f8ba8170b13049a11e6c09ffe3056a104a3bbe4ac5a955f4ba4fe93fc8cef27558a3eb9d2a529a2092761fb833b656cd48b9de6a