name: Build/Deploy App

on:
  push:
    branches: [ deploy-ci ]
  pull_request:
    branches: [ deploy-ci ]

env:
  KEY_JKS: ${{ secrets.UPLOAD_KEYSTORE }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  ALIAS_PASSWORD: ${{ secrets.STORE_PASSWORD }}

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Define environment variables
      uses: actions/checkout@v1
    - name: Define actions
      uses: actions/checkout@v1
    - name: setup-jav
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Create Version Number
      run: echo "VERSION '1.0.$GITHUB_RUN_ID'"
      env:
        VERSION_NAME: '1.0.$GITHUB_RUN_ID'
        VERSION_CODE: '$GITHUB_RUN_ID'

    - name: Directory Content
      run: ls android/
    - name: Upload Secret Key
      run: echo $UPLOAD_KEYSTORE > android/upload-keystore.jks 
    - name: Directory Content 2
      run: ls android/ 
      
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.2'
        channel: 'stable'
    - run: flutter --version

    - name: Build  APK
      run: flutter build apk

    - name: Save APK File
      uses: actions/upload-artifact@v3
      with:
        name: tactictrade-apk
        path: "build/app/outputs/apk/release/*"

    - name: Build appbundle
      run: flutter build appbundle

    - name: Save Bundle File
      uses: actions/upload-artifact@v3      
      with:
        name: tactictrade-appbundle
        path: "build/app/outputs/bundle/release/*"